apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: serviceA
  namespace: l5ddemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: serviceA
    spec:
      containers:
      - name: l5ddemo-service
        image: horzsolt/l5ddemo
        env:
        - name: "SERVICE_NAME"
          value: "Service-A"
        - name: "RESPONSE_DELAY"
          value: "30"
        ports:
          - name: web
            containerPort: 8080
        readinessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 10
        livenessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 180
---
apiVersion: v1
kind: Service
metadata:
  name: serviceA
  namespace: l5ddemo
  labels:
    app: serviceA
spec:
  type: NodePort
  ports:
    - name: web
      port: 8080
      targetPort: web
  selector:
    app: serviceA
