apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: service-a
#  namespace: l5ddemo
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: l5ddemo-service
        image: 10.0.0.252/horzsolt/l5ddemo
        env:
        - name: "SERVICE_NAME"
          value: "Service-a"
        - name: "RESPONSE_LATENCY"
          value: "0"
        - name: "POD_IP"
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: "NODE_NAME"
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: "HOST_IP"
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: "HTTP_PROXY_IP"
#          value: $(NODE_NAME)
          value: "192.168.99.100"
        - name: "HTTP_PROXY_PORT"
#          value: "4140"
          value: "31012"
        - name: "TARGET"
          value: "service-b.default"
        ports:
          - name: web
            containerPort: 8080
        readinessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 10
        livenessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 180
      - name: kubectl
        image: buoyantio/kubectl:v1.4.0
        args:
        - proxy
        - "-p"
        - "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
#  namespace: l5ddemo
  labels:
    app: service-a
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: service-a
