apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: service-b
#  namespace: l5ddemo
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: l5ddemo-service
        image: 10.0.0.252/horzsolt/l5ddemo
        env:
        - name: "SERVICE_NAME"
          value: "Service-b"
        - name: "RESPONSE_LATENCY"
          value: "0"
        - name: "POD_IP"
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: "NODE_NAME"
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: "HTTP_PROXY"
          value: $(NODE_NAME):4140
        - name: "TARGET"
          value: "service-c.default"
        ports:
          - name: web
            containerPort: 8080
        readinessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 10
        livenessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 180
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
#  namespace: l5ddemo
  labels:
    app: service-b
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: service-b
